service: serverless

plugins:
  - serverless-offline
  
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  region: us-east-1

functions:
  hello:
    handler: handler.hello
    events:
      - http: GET hello
